In [1]:
from utils import  init_data
train_schedules,met_stat_locations,coords=init_data()

Directory 'data/gtfs/' already exists.
Response Code: 200
Directory 'data/gtfs/latest/' created successfully!
Extracting data/gtfs/latest/gtfs
agency.txt
calendar.txt
feed_info.txt
routes.txt
shapes.txt
stops.txt
stop_times.txt
trips.txt
2 ['Budapest-Nyugati', 'Újpest', 'Pilisvörösvár', 'Piliscsaba', 'Solymár', 'Üröm', 'Dorog', 'Esztergom']
Getting data for Budapest-Nyugati
Getting data for Újpest
Getting data for Pilisvörösvár
Getting data for Piliscsaba
Getting data for Solymár
Getting data for Üröm
Getting data for Dorog
Getting data for Esztergom
147 ['Kiskunfélegyháza', 'Gátér', 'Csongrád', 'Szentes', 'Fábiánsebestyén', 'Gádoros', 'Orosháza']
Getting data for Kiskunfélegyháza
Getting data for Gátér
Getting data for Csongrád
Getting data for Szentes
Getting data for Fábiánsebestyén
Getting data for Gádoros
Getting data for Orosháza
-> Pulling  2048
-> Pulling  2049
-> Pulling  2050
-> Pulling  2051
-> Pulling  2052
-> Pulling  2053
-> Pulling  2054
-> Pulling  2055
-> Pulling  2056
-> Pulling  2057
-> Pulling  2058
-> Pulling  2060
-> Pulling  2061
-> Pulling  2062
Full nan col? ('Unnamed: 5_level_0', 'A pillanatnyi késés 8 perc.', 'Unnamed: 5_level_2', 'Unnamed: 5_level_3') True
Full nan col? ('Unnamed: 6_level_0', 'A pillanatnyi késés 8 perc.', 'Unnamed: 6_level_2', 'Unnamed: 6_level_3') True
Full nan col? ('Unnamed: 7_level_0', 'A pillanatnyi késés 8 perc.', 'Unnamed: 7_level_2', 'Unnamed: 7_level_3') True
Full nan col? ('Unnamed: 8_level_0', 'A pillanatnyi késés 8 perc.', 'Unnamed: 8_level_2', 'Unnamed: 8_level_3') True
-> Pulling  2063
-> Pulling  2064
-> Pulling  2065
-> Pulling  2066
-> Pulling  2067
-> Pulling  2068
-> Pulling  2071
-> Pulling  2072
-> Pulling  2073
-> Pulling  2074
-> Pulling  2075
-> Pulling  2076
-> Pulling  2077
Full nan col? ('Unnamed: 5_level_0', 'A pillanatnyi késés 8 perc.', 'Unnamed: 5_level_2', 'Unnamed: 5_level_3') True
Full nan col? ('Unnamed: 6_level_0', 'A pillanatnyi késés 8 perc.', 'Unnamed: 6_level_2', 'Unnamed: 6_level_3') True
Full nan col? ('Unnamed: 7_level_0', 'A pillanatnyi késés 8 perc.', 'Unnamed: 7_level_2', 'Unnamed: 7_level_3') True
Full nan col? ('Unnamed: 8_level_0', 'A pillanatnyi késés 8 perc.', 'Unnamed: 8_level_2', 'Unnamed: 8_level_3') True
-> Pulling  2078
-> Pulling  2081
-> Pulling  2082
-> Pulling  2083
-> Pulling  2084
-> Pulling  2085
-> Pulling  2086
-> Pulling  2087
-> Pulling  2088
-> Pulling  2117
-> Pulling  2127
-> Pulling  2171
-> Pulling  2178
-> Pulling  2181
-> Pulling  3210
-> Pulling  3211
-> Pulling  2188
-> Pulling  3212
-> Pulling  3213
-> Pulling  3214
-> Pulling  3215
-> Pulling  3216
-> Pulling  3217
-> Pulling  3218
-> Pulling  3219
-> Pulling  3220
-> Pulling  3221
-> Pulling  3222
-> Pulling  3223
-> Pulling  3224
-> Pulling  3226
-> Pulling  3227
-> Pulling  3228
-> Pulling  3229
-> Pulling  3230
-> Pulling  3231
-> Pulling  3232
-> Pulling  3233
-> Pulling  3234
-> Pulling  3235
-> Pulling  3236
-> Pulling  3237
-> Pulling  3238
-> Pulling  3239
-> Pulling  3240
-> Pulling  3241
-> Pulling  3242
-> Pulling  3243
-> Pulling  3244
-> Pulling  3245
-> Pulling  3246
-> Pulling  3247
-> Pulling  3248
-> Pulling  3249
-> Pulling  3251
-> Pulling  3252
-> Pulling  3253
-> Pulling  3254
-> Pulling  3255
-> Pulling  3256
-> Pulling  3257
-> Pulling  3258
-> Pulling  3259
-> Pulling  3261
-> Pulling  3262
Full nan col? ('Unnamed: 5_level_0', 'A pillanatnyi késés 7 perc.', 'Unnamed: 5_level_2', 'Unnamed: 5_level_3') True
Full nan col? ('Unnamed: 6_level_0', 'A pillanatnyi késés 7 perc.', 'Unnamed: 6_level_2', 'Unnamed: 6_level_3') True
Full nan col? ('Unnamed: 7_level_0', 'A pillanatnyi késés 7 perc.', 'Unnamed: 7_level_2', 'Unnamed: 7_level_3') True
Full nan col? ('Unnamed: 8_level_0', 'A pillanatnyi késés 7 perc.', 'Unnamed: 8_level_2', 'Unnamed: 8_level_3') True
-> Pulling  3263
-> Pulling  3264
-> Pulling  3265
-> Pulling  3266
-> Pulling  3267
-> Pulling  3268
-> Pulling  3269
-> Pulling  3272
-> Pulling  3273
-> Pulling  3274
-> Pulling  3275
-> Pulling  3276
-> Pulling  3277
-> Pulling  3278
-> Pulling  3282
-> Pulling  3283
-> Pulling  3284
-> Pulling  3285
-> Pulling  3286
-> Pulling  3287
-> Pulling  2010
-> Pulling  2011
-> Pulling  2012
-> Pulling  2013
-> Pulling  2014
-> Pulling  2015
-> Pulling  2016
-> Pulling  2017
-> Pulling  2018
-> Pulling  2019
-> Pulling  2021
-> Pulling  2022
-> Pulling  2023
-> Pulling  2024
-> Pulling  2025
-> Pulling  2026
-> Pulling  2027
-> Pulling  2028
-> Pulling  2029
-> Pulling  2030
-> Pulling  2031
-> Pulling  2032
-> Pulling  2033
-> Pulling  2034
-> Pulling  2035
-> Pulling  2036
-> Pulling  2037
-> Pulling  2038
-> Pulling  2039
-> Pulling  2040
-> Pulling  2041
-> Pulling  2042
-> Pulling  2043
-> Pulling  2044
-> Pulling  2045
-> Pulling  2046
-> Pulling  2047
-> Pulling  37410
-> Pulling  37412
-> Pulling  37414
-> Pulling  37415
-> Pulling  37416
-> Pulling  37417
-> Pulling  37418
-> Pulling  37419
-> Pulling  37421
-> Pulling  37428
-> Pulling  37431
-> Pulling  37435
-> Pulling  37438
-> Pulling  37439
-> Pulling  37461
-> Pulling  32610
-> Pulling  32612
-> Pulling  32613
-> Pulling  32614
-> Pulling  32616
-> Pulling  32617
-> Pulling  32619
-> Pulling  32626
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2060
2061
2062
2063
2064
2065
2066
2067
2068
2071
2072
2073
2074
2075
2076
2077
2078
2081
2082
2083
2084
2085
2086
2087
2088
2117
2127
2171
2178
2181
3210
3211
2188
3212
3213
3214
3215
3216
3217
3218
3219
3220
3221
3222
3223
3224
3226
3227
3228
3229
3230
3231
3232
3233
3234
3235
3236
3237
3238
3239
3240
3241
3242
3243
3244
3245
3246
3247
3248
3249
3251
3252
3253
3254
3255
3256
3257
3258
3259
3261
3262
3263
3264
3265
3266
3267
3268
3269
3272
3273
3274
3275
3276
3277
3278
3282
3283
3284
3285
3286
3287
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
37410
37412
37414
37415
37416
37417
37418
37419
37421
37428
37431
37435
37438
37439
37461
32610
32612
32613
32614
32616
32617
32619
32626

C:\Users\ELTE\Train_Data_Collection\utils.py:548: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shapes_with_nums['VONATSZAM'] = shapes_with_nums['numbers'].astype(int)
C:\Users\ELTE\Train_Data_Collection\utils.py:551: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shapes_with_names['NEV'] = shapes_with_names['name']

{'cod': '200', 'message': 0, 'cnt': 40, 'list': [{'dt': 1743066000, 'main': {'temp': 16.24, 'feels_like': 15.25, 'temp_min': 14.58, 'temp_max': 16.24, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 992, 'humidity': 51, 'temp_kf': 1.66}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 4.57, 'deg': 51, 'gust': 7.85}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-27 09:00:00'}, {'dt': 1743076800, 'main': {'temp': 16.3, 'feels_like': 15.21, 'temp_min': 16.3, 'temp_max': 16.43, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 990, 'humidity': 47, 'temp_kf': -0.13}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 33}, 'wind': {'speed': 5.4, 'deg': 62, 'gust': 7.82}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-27 12:00:00'}, {'dt': 1743087600, 'main': {'temp': 15.59, 'feels_like': 14.43, 'temp_min': 15.26, 'temp_max': 15.59, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 989, 'humidity': 47, 'temp_kf': 0.33}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 67}, 'wind': {'speed': 5.49, 'deg': 77, 'gust': 7.45}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-27 15:00:00'}, {'dt': 1743098400, 'main': {'temp': 12.74, 'feels_like': 11.51, 'temp_min': 12.74, 'temp_max': 12.74, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 990, 'humidity': 55, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 98}, 'wind': {'speed': 4.36, 'deg': 54, 'gust': 9.16}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-27 18:00:00'}, {'dt': 1743109200, 'main': {'temp': 10.35, 'feels_like': 8.93, 'temp_min': 10.35, 'temp_max': 10.35, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 990, 'humidity': 57, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 99}, 'wind': {'speed': 5.88, 'deg': 32, 'gust': 12.26}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-27 21:00:00'}, {'dt': 1743120000, 'main': {'temp': 9.5, 'feels_like': 6.71, 'temp_min': 9.5, 'temp_max': 9.5, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 989, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 99}, 'wind': {'speed': 5.7, 'deg': 28, 'gust': 12.02}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-28 00:00:00'}, {'dt': 1743130800, 'main': {'temp': 8.69, 'feels_like': 5.74, 'temp_min': 8.69, 'temp_max': 8.69, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 988, 'humidity': 57, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.56, 'deg': 22, 'gust': 12.49}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-28 03:00:00'}, {'dt': 1743141600, 'main': {'temp': 9.07, 'feels_like': 6.59, 'temp_min': 9.07, 'temp_max': 9.07, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 988, 'humidity': 58, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 90}, 'wind': {'speed': 4.6, 'deg': 22, 'gust': 10.56}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-28 06:00:00'}, {'dt': 1743152400, 'main': {'temp': 12.13, 'feels_like': 10.78, 'temp_min': 12.13, 'temp_max': 12.13, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 987, 'humidity': 53, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.28, 'deg': 32, 'gust': 7.17}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-28 09:00:00'}, {'dt': 1743163200, 'main': {'temp': 12.52, 'feels_like': 11.52, 'temp_min': 12.52, 'temp_max': 12.52, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 986, 'humidity': 65, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.87, 'deg': 96, 'gust': 7.62}, 'visibility': 10000, 'pop': 0.3, 'rain': {'3h': 0.51}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-28 12:00:00'}, {'dt': 1743174000, 'main': {'temp': 11.78, 'feels_like': 11.08, 'temp_min': 11.78, 'temp_max': 11.78, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 985, 'humidity': 79, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.06, 'deg': 55, 'gust': 9.65}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 2.23}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-28 15:00:00'}, {'dt': 1743184800, 'main': {'temp': 12.04, 'feels_like': 11.23, 'temp_min': 12.04, 'temp_max': 12.04, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 984, 'humidity': 74, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.98, 'deg': 52, 'gust': 9.11}, 'visibility': 10000, 'pop': 0.8, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-28 18:00:00'}, {'dt': 1743195600, 'main': {'temp': 11.27, 'feels_like': 10.62, 'temp_min': 11.27, 'temp_max': 11.27, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 984, 'humidity': 83, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 91}, 'wind': {'speed': 1.46, 'deg': 76, 'gust': 8.46}, 'visibility': 10000, 'pop': 0.44, 'rain': {'3h': 0.22}, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-28 21:00:00'}, {'dt': 1743206400, 'main': {'temp': 10.81, 'feels_like': 10.3, 'temp_min': 10.81, 'temp_max': 10.81, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 982, 'humidity': 90, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 96}, 'wind': {'speed': 1.93, 'deg': 48, 'gust': 4.11}, 'visibility': 10000, 'pop': 0.79, 'rain': {'3h': 1.33}, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-29 00:00:00'}, {'dt': 1743217200, 'main': {'temp': 10.78, 'feels_like': 10.13, 'temp_min': 10.78, 'temp_max': 10.78, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 981, 'humidity': 85, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.25, 'deg': 59, 'gust': 8.67}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 0.41}, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-29 03:00:00'}, {'dt': 1743228000, 'main': {'temp': 10.13, 'feels_like': 9.63, 'temp_min': 10.13, 'temp_max': 10.13, 'pressure': 1003, 'sea_level': 1003, 'grnd_level': 981, 'humidity': 93, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.41, 'deg': 64, 'gust': 10.54}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 1.07}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-29 06:00:00'}, {'dt': 1743238800, 'main': {'temp': 10.42, 'feels_like': 9.84, 'temp_min': 10.42, 'temp_max': 10.42, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 981, 'humidity': 89, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.58, 'deg': 88, 'gust': 12.56}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 1.13}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-29 09:00:00'}, {'dt': 1743249600, 'main': {'temp': 10.27, 'feels_like': 9.62, 'temp_min': 10.27, 'temp_max': 10.27, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 981, 'humidity': 87, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.98, 'deg': 68, 'gust': 9.6}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 2.17}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-29 12:00:00'}, {'dt': 1743260400, 'main': {'temp': 11.43, 'feels_like': 10.72, 'temp_min': 11.43, 'temp_max': 11.43, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 982, 'humidity': 80, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.65, 'deg': 59, 'gust': 7.38}, 'visibility': 10000, 'pop': 0.07, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-29 15:00:00'}, {'dt': 1743271200, 'main': {'temp': 10.19, 'feels_like': 9.54, 'temp_min': 10.19, 'temp_max': 10.19, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 983, 'humidity': 87, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 1.95, 'deg': 10, 'gust': 4}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-29 18:00:00'}, {'dt': 1743282000, 'main': {'temp': 9.06, 'feels_like': 8.03, 'temp_min': 9.06, 'temp_max': 9.06, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 984, 'humidity': 91, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 99}, 'wind': {'speed': 2.08, 'deg': 338, 'gust': 3.79}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-29 21:00:00'}, {'dt': 1743292800, 'main': {'temp': 8.54, 'feels_like': 7.38, 'temp_min': 8.54, 'temp_max': 8.54, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 984, 'humidity': 92, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 98}, 'wind': {'speed': 2.13, 'deg': 330, 'gust': 3.85}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-30 00:00:00'}, {'dt': 1743303600, 'main': {'temp': 8.59, 'feels_like': 7.83, 'temp_min': 8.59, 'temp_max': 8.59, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 984, 'humidity': 93, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 98}, 'wind': {'speed': 1.7, 'deg': 307, 'gust': 2.34}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-30 03:00:00'}, {'dt': 1743314400, 'main': {'temp': 9.34, 'feels_like': 8.68, 'temp_min': 9.34, 'temp_max': 9.34, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 985, 'humidity': 91, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 99}, 'wind': {'speed': 1.71, 'deg': 315, 'gust': 3.76}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-30 06:00:00'}, {'dt': 1743325200, 'main': {'temp': 9.68, 'feels_like': 9.46, 'temp_min': 9.68, 'temp_max': 9.68, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 986, 'humidity': 91, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 1.34, 'deg': 323, 'gust': 2.53}, 'visibility': 10000, 'pop': 0.74, 'rain': {'3h': 0.63}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-30 09:00:00'}, {'dt': 1743336000, 'main': {'temp': 9.85, 'feels_like': 9.37, 'temp_min': 9.85, 'temp_max': 9.85, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 986, 'humidity': 92, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 1.61, 'deg': 310, 'gust': 3.73}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 2.14}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-30 12:00:00'}, {'dt': 1743346800, 'main': {'temp': 9.58, 'feels_like': 8, 'temp_min': 9.58, 'temp_max': 9.58, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 986, 'humidity': 90, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.01, 'deg': 306, 'gust': 6.19}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 0.47}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-30 15:00:00'}, {'dt': 1743357600, 'main': {'temp': 8.6, 'feels_like': 6.58, 'temp_min': 8.6, 'temp_max': 8.6, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 987, 'humidity': 87, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.42, 'deg': 315, 'gust': 7.73}, 'visibility': 10000, 'pop': 0.33, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-30 18:00:00'}, {'dt': 1743368400, 'main': {'temp': 7.49, 'feels_like': 4.81, 'temp_min': 7.49, 'temp_max': 7.49, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 987, 'humidity': 87, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.21, 'deg': 320, 'gust': 8.53}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 1.41}, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-30 21:00:00'}, {'dt': 1743379200, 'main': {'temp': 6.52, 'feels_like': 3.4, 'temp_min': 6.52, 'temp_max': 6.52, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 987, 'humidity': 88, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 4.64, 'deg': 326, 'gust': 8.76}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 2.45}, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-31 00:00:00'}, {'dt': 1743390000, 'main': {'temp': 5.99, 'feels_like': 3.13, 'temp_min': 5.99, 'temp_max': 5.99, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 987, 'humidity': 88, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.9, 'deg': 332, 'gust': 7.7}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 2.38}, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-31 03:00:00'}, {'dt': 1743400800, 'main': {'temp': 6.22, 'feels_like': 3.57, 'temp_min': 6.22, 'temp_max': 6.22, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 989, 'humidity': 86, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.63, 'deg': 332, 'gust': 7.26}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 0.65}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-31 06:00:00'}, {'dt': 1743411600, 'main': {'temp': 10.19, 'feels_like': 9.01, 'temp_min': 10.19, 'temp_max': 10.19, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 991, 'humidity': 67, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 99}, 'wind': {'speed': 3.17, 'deg': 352, 'gust': 4.31}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-31 09:00:00'}, {'dt': 1743422400, 'main': {'temp': 12.62, 'feels_like': 11.37, 'temp_min': 12.62, 'temp_max': 12.62, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 992, 'humidity': 55, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 97}, 'wind': {'speed': 2.27, 'deg': 355, 'gust': 3.12}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-31 12:00:00'}, {'dt': 1743433200, 'main': {'temp': 12.64, 'feels_like': 11.42, 'temp_min': 12.64, 'temp_max': 12.64, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 993, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 1.99, 'deg': 302, 'gust': 2.79}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-03-31 15:00:00'}, {'dt': 1743444000, 'main': {'temp': 10.85, 'feels_like': 9.74, 'temp_min': 10.85, 'temp_max': 10.85, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 995, 'humidity': 67, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.36, 'deg': 320, 'gust': 5.5}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-31 18:00:00'}, {'dt': 1743454800, 'main': {'temp': 9.74, 'feels_like': 8.84, 'temp_min': 9.74, 'temp_max': 9.74, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 995, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.06, 'deg': 337, 'gust': 3.17}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-03-31 21:00:00'}, {'dt': 1743465600, 'main': {'temp': 9.01, 'feels_like': 7.68, 'temp_min': 9.01, 'temp_max': 9.01, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 995, 'humidity': 74, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.46, 'deg': 323, 'gust': 4.38}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-04-01 00:00:00'}, {'dt': 1743476400, 'main': {'temp': 8.3, 'feels_like': 6.89, 'temp_min': 8.3, 'temp_max': 8.3, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 994, 'humidity': 76, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.39, 'deg': 335, 'gust': 4.17}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-04-01 03:00:00'}, {'dt': 1743487200, 'main': {'temp': 8.32, 'feels_like': 6.68, 'temp_min': 8.32, 'temp_max': 8.32, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 994, 'humidity': 82, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 2.72, 'deg': 348, 'gust': 7.84}, 'visibility': 10000, 'pop': 0.4, 'rain': {'3h': 0.39}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-04-01 06:00:00'}], 'city': {'id': 7284843, 'name': 'Budapest II. kerület', 'coord': {'lat': 47.5073, 'lon': 19.0314}, 'country': 'HU', 'population': 88729, 'timezone': 3600, 'sunrise': 1743049958, 'sunset': 1743095138}}

In [2]:
train_schedules

,VONAT_,IND_TERV_first,ERK_TERV_last,KOZLEKEDESI_NAP_last,Állomás_first,Állomás_last,NEV_first,VONATSZAM_L,SZH_KOD,stop_lat,...,POLGARI_NEV,stop_name,Legközelebbi met. állomás,Loc,Lat,Lon,tx,t,tn,r
0,2048,2025-03-27 19:51:00,2025-03-27 20:56:00,2025-03-27,Budapest-Nyugati,Esztergom,Z72,552048,10033,47.510833,...,Budapest-Nyugati,Budapest-Nyugati,Budapest,Budapest,47.507300,19.031400,16.43,12.485,8.54,8.3105
1,2048,2025-03-27 19:51:00,2025-03-27 20:56:00,2025-03-27,Budapest-Nyugati,Esztergom,Z72,552048,10033,47.510833,...,Budapest-Nyugati,Budapest-Nyugati,Budapest,Budapest,47.507300,19.031400,16.43,12.485,8.54,8.3105
2,2049,2025-03-27 05:35:00,2025-03-27 06:39:00,2025-03-27,Esztergom,Budapest-Nyugati,Z72,552049,1511,47.777500,...,Esztergom,Esztergom,Budapest,Budapest,47.507300,19.031400,16.43,12.485,8.54,8.3105
3,2049,2025-03-27 05:35:00,2025-03-27 06:39:00,2025-03-27,Esztergom,Budapest-Nyugati,Z72,552049,1511,47.777500,...,Esztergom,Esztergom,Budapest,Budapest,47.507300,19.031400,16.43,12.485,8.54,8.3105
4,2050,2025-03-27 05:21:00,2025-03-27 06:26:00,2025-03-27,Budapest-Nyugati,Esztergom,Z72,552050,10033,47.510833,...,Budapest-Nyugati,Budapest-Nyugati,Budapest,Budapest,47.507300,19.031400,16.43,12.485,8.54,8.3105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,32617,2025-03-27 07:40:00,2025-03-27 09:22:00,2025-03-27,Hódmezővásárhely,Kiskunfélegyháza,személyvonat,5532617,18572,46.413333,...,Hódmezővásárhely,Hódmezővásárhely,Szeged,Szeged,46.289690,20.185060,14.67,11.265,7.86,24.5930
340,32619,2025-03-27 05:40:00,2025-03-27 07:22:00,2025-03-27,Hódmezővásárhely,Kiskunfélegyháza,személyvonat,5532619,18572,46.413333,...,Hódmezővásárhely,Hódmezővásárhely,Szeged,Szeged,46.251943,20.114371,14.49,11.110,7.73,25.0653
341,32619,2025-03-27 05:40:00,2025-03-27 07:22:00,2025-03-27,Hódmezővásárhely,Kiskunfélegyháza,személyvonat,5532619,18572,46.413333,...,Hódmezővásárhely,Hódmezővásárhely,Szeged,Szeged,46.289690,20.185060,14.67,11.265,7.86,24.5930
342,32626,2025-03-27 17:38:00,2025-03-27 19:19:00,2025-03-27,Kiskunfélegyháza,Hódmezővásárhely,személyvonat,5532626,17137,46.706944,...,Kiskunfélegyháza,Kiskunfélegyháza,Szeged,Szeged,46.251943,20.114371,14.49,11.110,7.73,25.0653
343,32626,2025-03-27 17:38:00,2025-03-27 19:19:00,2025-03-27,Kiskunfélegyháza,Hódmezővásárhely,személyvonat,5532626,17137,46.706944,...,Kiskunfélegyháza,Kiskunfélegyháza,Szeged,Szeged,46.289690,20.185060,14.67,11.265,7.86,24.5930

In [3]:
met_stat_locations

            Loc        Lat        Lon
0      Budapest  47.507300  19.031400
1      Debrecen  47.531438  21.625387
2     Keszthely  46.742617  17.227400
3       Miskolc  48.123882  20.837100
4   Nyiregyhaza  47.969911  21.767344
5          Pecs  46.087188  18.277832
6        Sopron  47.687800  16.603233
7        Szeged  46.251943  20.114371
8   Szombathely  47.249480  16.623060
9       Turkeve  47.105900  20.734733
10     Budapest  47.507300  19.031400
11     Debrecen  47.531438  21.625387
12    Keszthely  46.742617  17.227400
13      Miskolc  48.123882  20.837100
14  Nyiregyhaza  47.969911  21.767344
15         Pecs  46.087188  18.277832
16       Sopron  47.687800  16.603233
17       Szeged  46.289690  20.185060
18  Szombathely  47.249480  16.623060
19      Turkeve  47.105900  20.734733

In [4]:
coords

,SZH_KOD,stop_lat,stop_lon,SZH_NEV,POLGARI_NEV,stop_name,Legközelebbi met. állomás
1,7229,46.152778,18.073611,Abaliget,Abaliget,Abaliget,Pecs
3,13326,48.309444,21.198333,Abaújkér,Abaújkér,Abaújkér,Miskolc
5,13300,48.286944,21.181667,Abaújszántó,Abaújszántó,Abaújszántó,Miskolc
6,13318,48.268333,21.179722,Abaújszántói fürdő,Abaújszántói fürdő,Abaújszántói fürdő,Miskolc
8,1305,47.690833,17.540556,Abda,Abda,Abda,Sopron
...,...,...,...,...,...,...,...
2677,10587,47.685833,19.283611,Őrbottyán,Őrbottyán,Őrbottyán,Budapest
2678,10975,48.078611,19.403889,Őrhalom,Őrhalom,Őrhalom,Budapest
2682,5074,46.828889,16.415278,Őriszentpéter,Őriszentpéter,Őriszentpéter,Szombathely
2684,5561,46.297778,16.887778,Őrtilos,Őrtilos,Őrtilos,Keszthely
2685,44602,46.390000,20.016111,Őszeszék,Őszeszék,Őszeszék,Szeged

In [9]:
from utils import get_recent_trains
# all trains that is
recent_trains, resp = get_recent_trains(train_schedules)

C:\Users\ELTE\Train_Data_Collection\utils.py:628: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recent_trains['Vonatszam']=recent_trains['VONAT_'].astype(int)
C:\Users\ELTE\Train_Data_Collection\utils.py:629: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recent_trains['Nev']=recent_trains['NEV_first']+' : '+recent_trains['@Relation']
C:\Users\ELTE\Train_Data_Collection\utils.py:630: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recent_trains['Nap']=recent_trains['KOZLEKEDESI_NAP_last'].astype(str)

In [10]:
recent_trains

,Vonatszam,Lat,Lon,Nev,Nap,Keses
0,2072,47.635170,18.83379,Z72 : Budapest-Nyugati - Esztergom,2025-03-27,4.0
1,2072,47.635170,18.83379,Z72 : Budapest-Nyugati - Esztergom,2025-03-27,4.0
2,2077,47.566020,19.04958,Z72 : Esztergom - Budapest-Nyugati,2025-03-27,7.0
3,2077,47.566020,19.04958,Z72 : Esztergom - Budapest-Nyugati,2025-03-27,7.0
4,2082,47.558708,19.07964,Z72 : Budapest-Nyugati - Esztergom,2025-03-27,0.0
5,2082,47.558708,19.07964,Z72 : Budapest-Nyugati - Esztergom,2025-03-27,0.0
6,2087,47.639190,18.82818,Z72 : Esztergom - Budapest-Nyugati,2025-03-27,1.0
7,2087,47.639190,18.82818,Z72 : Esztergom - Budapest-Nyugati,2025-03-27,1.0
8,3247,47.595080,18.96546,S76 : Pilisvörösvár - Rákos,2025-03-27,2.0
9,3247,47.595080,18.96546,S76 : Pilisvörösvár - Rákos,2025-03-27,2.0
10,3262,47.573400,19.01865,S76 : Rákos - Pilisvörösvár,2025-03-27,6.0
11,3262,47.573400,19.01865,S76 : Rákos - Pilisvörösvár,2025-03-27,6.0
12,37412,46.690200,19.92283,személyvonat : Kiskunfélegyháza - Szentes,2025-03-27,0.0
13,37412,46.690200,19.92283,személyvonat : Kiskunfélegyháza - Szentes,2025-03-27,0.0

In [13]:
no = recent_trains.iloc[0]['Vonatszam']

In [14]:
from utils import  get_train_data

data = get_train_data(no)

-> Pulling  2072

In [15]:
data

,Km,Állomás,Vágány,ERK_TERV,ERK_TENY,IND_TERV,IND_TENY,VONAT,KOZLEKEDESI_NAP,NEV,TiPUS,PLUSZ
0,0,Budapest-Nyugati,1,NaT,NaT,2025-03-27 09:21:00,2025-03-27 09:23:00,2072,2025-03-27,Z72,személyvonat,
1,8,Újpest,2,2025-03-27 09:31:00,2025-03-27 09:34:00,2025-03-27 09:32:00,2025-03-27 09:34:00,2072,2025-03-27,Z72,személyvonat,
2,10,Aquincum,1,2025-03-27 09:35:00,2025-03-27 09:37:00,2025-03-27 09:35:00,2025-03-27 09:37:00,2072,2025-03-27,Z72,személyvonat,
3,19,Solymár,2,2025-03-27 09:41:00,2025-03-27 09:43:00,2025-03-27 09:42:00,2025-03-27 09:44:00,2072,2025-03-27,Z72,személyvonat,
4,23,Pilisvörösvár,1,2025-03-27 09:46:00,2025-03-27 09:48:00,2025-03-27 09:47:00,2025-03-27 09:50:00,2072,2025-03-27,Z72,személyvonat,
5,25,Szabadságliget,mh,2025-03-27 09:49:00,2025-03-27 09:52:00,2025-03-27 09:49:00,2025-03-27 09:53:00,2072,2025-03-27,Z72,személyvonat,
6,31,Klotildliget,mh,2025-03-27 09:56:00,2025-03-27 09:59:00,2025-03-27 09:56:00,2025-03-27 10:01:00,2072,2025-03-27,Z72,személyvonat,
7,32,Piliscsaba,3,2025-03-27 09:59:00,2025-03-27 10:03:00,2025-03-27 10:00:00,2025-03-27 10:03:00,2072,2025-03-27,Z72,személyvonat,
8,36,Pilisjászfalu,mh,2025-03-27 10:04:00,2025-03-27 10:07:00,2025-03-27 10:04:00,2025-03-27 10:07:00,2072,2025-03-27,Z72,személyvonat,
9,39,Piliscsév,mh,2025-03-27 10:07:00,2025-03-27 10:11:00,2025-03-27 10:07:00,2025-03-27 10:11:00,2072,2025-03-27,Z72,személyvonat,
10,41,Leányvár,2,2025-03-27 10:10:00,2025-03-27 10:13:00,2025-03-27 10:11:00,2025-03-27 10:14:00,2072,2025-03-27,Z72,személyvonat,
11,46,Dorog,3,2025-03-27 10:16:00,2025-03-27 10:18:00,2025-03-27 10:17:00,2025-03-27 10:18:00,2072,2025-03-27,Z72,személyvonat,
12,49,Esztergom-Kertváros,1,2025-03-27 10:20:00,2025-03-27 10:21:00,2025-03-27 10:21:00,2025-03-27 10:21:00,2072,2025-03-27,Z72,személyvonat,
13,53,Esztergom,2,2025-03-27 10:26:00,2025-03-27 10:26:00,NaT,NaT,2072,2025-03-27,Z72,személyvonat,